#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BibliotecaRenta")]
	public partial class rentaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertClientes(Clientes instance);
    partial void UpdateClientes(Clientes instance);
    partial void DeleteClientes(Clientes instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    partial void InsertAutores(Autores instance);
    partial void UpdateAutores(Autores instance);
    partial void DeleteAutores(Autores instance);
    partial void InsertEditoriales(Editoriales instance);
    partial void UpdateEditoriales(Editoriales instance);
    partial void DeleteEditoriales(Editoriales instance);
    partial void InsertCategorias(Categorias instance);
    partial void UpdateCategorias(Categorias instance);
    partial void DeleteCategorias(Categorias instance);
    partial void InsertLenguajes(Lenguajes instance);
    partial void UpdateLenguajes(Lenguajes instance);
    partial void DeleteLenguajes(Lenguajes instance);
    partial void InsertVenta_Detalle(Venta_Detalle instance);
    partial void UpdateVenta_Detalle(Venta_Detalle instance);
    partial void DeleteVenta_Detalle(Venta_Detalle instance);
    partial void InsertVentas(Ventas instance);
    partial void UpdateVentas(Ventas instance);
    partial void DeleteVentas(Ventas instance);
    partial void InsertLibros(Libros instance);
    partial void UpdateLibros(Libros instance);
    partial void DeleteLibros(Libros instance);
    #endregion
		
		public rentaDataContext() : 
				base(global::datos.Properties.Settings.Default.BibliotecaRentaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public rentaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public rentaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public rentaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public rentaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Clientes> Clientes
		{
			get
			{
				return this.GetTable<Clientes>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<Autores> Autores
		{
			get
			{
				return this.GetTable<Autores>();
			}
		}
		
		public System.Data.Linq.Table<Editoriales> Editoriales
		{
			get
			{
				return this.GetTable<Editoriales>();
			}
		}
		
		public System.Data.Linq.Table<Categorias> Categorias
		{
			get
			{
				return this.GetTable<Categorias>();
			}
		}
		
		public System.Data.Linq.Table<Lenguajes> Lenguajes
		{
			get
			{
				return this.GetTable<Lenguajes>();
			}
		}
		
		public System.Data.Linq.Table<Venta_Detalle> Venta_Detalle
		{
			get
			{
				return this.GetTable<Venta_Detalle>();
			}
		}
		
		public System.Data.Linq.Table<Ventas> Ventas
		{
			get
			{
				return this.GetTable<Ventas>();
			}
		}
		
		public System.Data.Linq.Table<Libros> Libros
		{
			get
			{
				return this.GetTable<Libros>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarCliente")]
		public int sp_ActualizarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClienteID", DbType="Int")] System.Nullable<int> clienteID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="NVarChar(50)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="NVarChar(100)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="NVarChar(20)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clienteID, nombre, apellido, direccion, telefono, email);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EliminarCliente")]
		public int sp_EliminarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClienteID", DbType="Int")] System.Nullable<int> clienteID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clienteID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_LeerCliente")]
		public ISingleResult<sp_LeerClienteResult> sp_LeerCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClienteID", DbType="Int")] System.Nullable<int> clienteID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clienteID);
			return ((ISingleResult<sp_LeerClienteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertarCliente")]
		public int sp_InsertarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="NVarChar(50)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="NVarChar(100)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="NVarChar(20)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, apellido, direccion, telefono, email);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ListarClientes")]
		public ISingleResult<sp_ListarClientesResult> sp_ListarClientes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ListarClientesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarUsuario")]
		public int sp_ActualizarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreUsuario", DbType="NVarChar(50)")] string nombreUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="NVarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contraseña", DbType="NVarChar(50)")] string contraseña, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rol", DbType="NVarChar(20)")] string rol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioID, nombreUsuario, correo, contraseña, rol);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EliminarUsuario")]
		public int sp_EliminarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertarUsuario")]
		public int sp_InsertarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreUsuario", DbType="NVarChar(50)")] string nombreUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="NVarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contraseña", DbType="NVarChar(50)")] string contraseña, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rol", DbType="NVarChar(20)")] string rol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreUsuario, correo, contraseña, rol);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_LeerUsuario")]
		public ISingleResult<sp_LeerUsuarioResult> sp_LeerUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioID);
			return ((ISingleResult<sp_LeerUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ListarUsuarios")]
		public ISingleResult<sp_ListarUsuariosResult> sp_ListarUsuarios()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ListarUsuariosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CrearAutor")]
		public int sp_CrearAutor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="NVarChar(50)")] string apellido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, apellido);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EliminarAutor")]
		public int sp_EliminarAutor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AutorID", DbType="Int")] System.Nullable<int> autorID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), autorID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ListarAutores")]
		public ISingleResult<sp_ListarAutoresResult> sp_ListarAutores()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ListarAutoresResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ModificarAutor")]
		public int sp_ModificarAutor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AutorID", DbType="Int")] System.Nullable<int> autorID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="NVarChar(50)")] string apellido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), autorID, nombre, apellido);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ModificarEditorial")]
		public int sp_ModificarEditorial([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EditorialID", DbType="Int")] System.Nullable<int> editorialID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreEditorial", DbType="NVarChar(50)")] string nombreEditorial)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), editorialID, nombreEditorial);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ListarEditoriales")]
		public ISingleResult<sp_ListarEditorialesResult> sp_ListarEditoriales()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ListarEditorialesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CrearEditorial")]
		public int sp_CrearEditorial([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EliminarEditorial")]
		public int sp_EliminarEditorial([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EditorialID", DbType="Int")] System.Nullable<int> editorialID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), editorialID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CrearCategoria")]
		public int sp_CrearCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreCategoria", DbType="NVarChar(50)")] string nombreCategoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreCategoria);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EliminarCategoria")]
		public int sp_EliminarCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoriaID", DbType="Int")] System.Nullable<int> categoriaID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoriaID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ListarCategorias")]
		public ISingleResult<sp_ListarCategoriasResult> sp_ListarCategorias()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ListarCategoriasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ModificarCategoria")]
		public int sp_ModificarCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoriaID", DbType="Int")] System.Nullable<int> categoriaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreCategoria", DbType="NVarChar(50)")] string nombreCategoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoriaID, nombreCategoria);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ModificarLenguaje")]
		public int sp_ModificarLenguaje([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LenguajeID", DbType="Int")] System.Nullable<int> lenguajeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreLenguaje", DbType="NVarChar(50)")] string nombreLenguaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lenguajeID, nombreLenguaje);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ListarLenguajes")]
		public ISingleResult<sp_ListarLenguajesResult> sp_ListarLenguajes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ListarLenguajesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EliminarLibro")]
		public int sp_EliminarLibro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LibroID", DbType="Int")] System.Nullable<int> libroID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), libroID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EliminarLenguaje")]
		public int sp_EliminarLenguaje([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LenguajeID", DbType="Int")] System.Nullable<int> lenguajeID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lenguajeID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CrearLenguaje")]
		public int sp_CrearLenguaje([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreLenguaje", DbType="NVarChar(50)")] string nombreLenguaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreLenguaje);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ListarVentas")]
		public ISingleResult<sp_ListarVentasResult> sp_ListarVentas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ListarVentasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertarVentaDetalle")]
		public int sp_InsertarVentaDetalle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VentaID", DbType="Int")] System.Nullable<int> ventaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LibroID", DbType="Int")] System.Nullable<int> libroID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Precio", DbType="Money")] System.Nullable<decimal> precio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ventaID, libroID, cantidad, precio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertarVenta")]
		public int sp_InsertarVenta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClienteID", DbType="Int")] System.Nullable<int> clienteID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaRenta", DbType="DateTime")] System.Nullable<System.DateTime> fechaRenta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaDevolucion", DbType="DateTime")] System.Nullable<System.DateTime> fechaDevolucion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total", DbType="Money")] System.Nullable<decimal> total, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewVentaID", DbType="Int")] ref System.Nullable<int> newVentaID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clienteID, usuarioID, fechaRenta, fechaDevolucion, total, newVentaID);
			newVentaID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ListarVentaDetalle")]
		public ISingleResult<sp_ListarVentaDetalleResult> sp_ListarVentaDetalle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VentaID", DbType="Int")] System.Nullable<int> ventaID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ventaID);
			return ((ISingleResult<sp_ListarVentaDetalleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ModificarLibro")]
		public int sp_ModificarLibro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LibroID", DbType="Int")] System.Nullable<int> libroID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Titulo", DbType="VarChar(255)")] string titulo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISBN", DbType="VarChar(20)")] string iSBN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoriaID", DbType="Int")] System.Nullable<int> categoriaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AutorID", DbType="Int")] System.Nullable<int> autorID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EditorialID", DbType="Int")] System.Nullable<int> editorialID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LenguajeID", DbType="Int")] System.Nullable<int> lenguajeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Stock", DbType="Int")] System.Nullable<int> stock, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="NVarChar(50)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Precio", DbType="Money")] System.Nullable<decimal> precio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), libroID, titulo, iSBN, categoriaID, autorID, editorialID, lenguajeID, stock, tipo, precio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CrearLibro")]
		public int sp_CrearLibro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Titulo", DbType="VarChar(255)")] string titulo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISBN", DbType="VarChar(20)")] string iSBN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoriaID", DbType="Int")] System.Nullable<int> categoriaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AutorID", DbType="Int")] System.Nullable<int> autorID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EditorialID", DbType="Int")] System.Nullable<int> editorialID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LenguajeID", DbType="Int")] System.Nullable<int> lenguajeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Stock", DbType="Int")] System.Nullable<int> stock, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="NVarChar(50)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Precio", DbType="Money")] System.Nullable<decimal> precio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), titulo, iSBN, categoriaID, autorID, editorialID, lenguajeID, stock, tipo, precio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ListarLibros")]
		public ISingleResult<sp_ListarLibrosResult> sp_ListarLibros()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ListarLibrosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_DevolverLibros")]
		public int sp_DevolverLibros([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VentaID", DbType="Int")] System.Nullable<int> ventaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaRealDevolucion", DbType="DateTime")] System.Nullable<System.DateTime> fechaRealDevolucion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ventaID, fechaRealDevolucion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_VistaVentas")]
		public ISingleResult<sp_VistaVentasResult> sp_VistaVentas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_VistaVentasResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clientes")]
	public partial class Clientes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ClienteID;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Email;
		
		private EntitySet<Ventas> _Ventas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnClienteIDChanging(int value);
    partial void OnClienteIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Clientes()
		{
			this._Ventas = new EntitySet<Ventas>(new Action<Ventas>(this.attach_Ventas), new Action<Ventas>(this.detach_Ventas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClienteID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ClienteID
		{
			get
			{
				return this._ClienteID;
			}
			set
			{
				if ((this._ClienteID != value))
				{
					this.OnClienteIDChanging(value);
					this.SendPropertyChanging();
					this._ClienteID = value;
					this.SendPropertyChanged("ClienteID");
					this.OnClienteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(100)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Clientes_Ventas", Storage="_Ventas", ThisKey="ClienteID", OtherKey="ClienteID")]
		public EntitySet<Ventas> Ventas
		{
			get
			{
				return this._Ventas;
			}
			set
			{
				this._Ventas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ventas(Ventas entity)
		{
			this.SendPropertyChanging();
			entity.Clientes = this;
		}
		
		private void detach_Ventas(Ventas entity)
		{
			this.SendPropertyChanging();
			entity.Clientes = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UsuarioID;
		
		private string _NombreUsuario;
		
		private string _Correo;
		
		private string _Contraseña;
		
		private string _Rol;
		
		private System.Nullable<System.DateTime> _FechaCreacion;
		
		private EntitySet<Ventas> _Ventas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsuarioIDChanging(int value);
    partial void OnUsuarioIDChanged();
    partial void OnNombreUsuarioChanging(string value);
    partial void OnNombreUsuarioChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnContraseñaChanging(string value);
    partial void OnContraseñaChanged();
    partial void OnRolChanging(string value);
    partial void OnRolChanged();
    partial void OnFechaCreacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaCreacionChanged();
    #endregion
		
		public Usuarios()
		{
			this._Ventas = new EntitySet<Ventas>(new Action<Ventas>(this.attach_Ventas), new Action<Ventas>(this.detach_Ventas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					this.OnUsuarioIDChanging(value);
					this.SendPropertyChanging();
					this._UsuarioID = value;
					this.SendPropertyChanged("UsuarioID");
					this.OnUsuarioIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="NVarChar(50)")]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this.OnNombreUsuarioChanging(value);
					this.SendPropertyChanging();
					this._NombreUsuario = value;
					this.SendPropertyChanged("NombreUsuario");
					this.OnNombreUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="NVarChar(50)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="NVarChar(50)")]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="NVarChar(20)")]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this.OnRolChanging(value);
					this.SendPropertyChanging();
					this._Rol = value;
					this.SendPropertyChanged("Rol");
					this.OnRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Ventas", Storage="_Ventas", ThisKey="UsuarioID", OtherKey="UsuarioID")]
		public EntitySet<Ventas> Ventas
		{
			get
			{
				return this._Ventas;
			}
			set
			{
				this._Ventas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ventas(Ventas entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_Ventas(Ventas entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Autores")]
	public partial class Autores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AutorID;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private EntitySet<Libros> _Libros;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAutorIDChanging(int value);
    partial void OnAutorIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    #endregion
		
		public Autores()
		{
			this._Libros = new EntitySet<Libros>(new Action<Libros>(this.attach_Libros), new Action<Libros>(this.detach_Libros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutorID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AutorID
		{
			get
			{
				return this._AutorID;
			}
			set
			{
				if ((this._AutorID != value))
				{
					this.OnAutorIDChanging(value);
					this.SendPropertyChanging();
					this._AutorID = value;
					this.SendPropertyChanged("AutorID");
					this.OnAutorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Autores_Libros", Storage="_Libros", ThisKey="AutorID", OtherKey="AutorID")]
		public EntitySet<Libros> Libros
		{
			get
			{
				return this._Libros;
			}
			set
			{
				this._Libros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Libros(Libros entity)
		{
			this.SendPropertyChanging();
			entity.Autores = this;
		}
		
		private void detach_Libros(Libros entity)
		{
			this.SendPropertyChanging();
			entity.Autores = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Editoriales")]
	public partial class Editoriales : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EditorialID;
		
		private string _NombreEditorial;
		
		private EntitySet<Libros> _Libros;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEditorialIDChanging(int value);
    partial void OnEditorialIDChanged();
    partial void OnNombreEditorialChanging(string value);
    partial void OnNombreEditorialChanged();
    #endregion
		
		public Editoriales()
		{
			this._Libros = new EntitySet<Libros>(new Action<Libros>(this.attach_Libros), new Action<Libros>(this.detach_Libros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditorialID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EditorialID
		{
			get
			{
				return this._EditorialID;
			}
			set
			{
				if ((this._EditorialID != value))
				{
					this.OnEditorialIDChanging(value);
					this.SendPropertyChanging();
					this._EditorialID = value;
					this.SendPropertyChanged("EditorialID");
					this.OnEditorialIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEditorial", DbType="NVarChar(50)")]
		public string NombreEditorial
		{
			get
			{
				return this._NombreEditorial;
			}
			set
			{
				if ((this._NombreEditorial != value))
				{
					this.OnNombreEditorialChanging(value);
					this.SendPropertyChanging();
					this._NombreEditorial = value;
					this.SendPropertyChanged("NombreEditorial");
					this.OnNombreEditorialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Editoriales_Libros", Storage="_Libros", ThisKey="EditorialID", OtherKey="EditorialID")]
		public EntitySet<Libros> Libros
		{
			get
			{
				return this._Libros;
			}
			set
			{
				this._Libros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Libros(Libros entity)
		{
			this.SendPropertyChanging();
			entity.Editoriales = this;
		}
		
		private void detach_Libros(Libros entity)
		{
			this.SendPropertyChanging();
			entity.Editoriales = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categorias")]
	public partial class Categorias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CategoriaID;
		
		private string _NombreCategoria;
		
		private EntitySet<Libros> _Libros;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategoriaIDChanging(int value);
    partial void OnCategoriaIDChanged();
    partial void OnNombreCategoriaChanging(string value);
    partial void OnNombreCategoriaChanged();
    #endregion
		
		public Categorias()
		{
			this._Libros = new EntitySet<Libros>(new Action<Libros>(this.attach_Libros), new Action<Libros>(this.detach_Libros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CategoriaID
		{
			get
			{
				return this._CategoriaID;
			}
			set
			{
				if ((this._CategoriaID != value))
				{
					this.OnCategoriaIDChanging(value);
					this.SendPropertyChanging();
					this._CategoriaID = value;
					this.SendPropertyChanged("CategoriaID");
					this.OnCategoriaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCategoria", DbType="NVarChar(50)")]
		public string NombreCategoria
		{
			get
			{
				return this._NombreCategoria;
			}
			set
			{
				if ((this._NombreCategoria != value))
				{
					this.OnNombreCategoriaChanging(value);
					this.SendPropertyChanging();
					this._NombreCategoria = value;
					this.SendPropertyChanged("NombreCategoria");
					this.OnNombreCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorias_Libros", Storage="_Libros", ThisKey="CategoriaID", OtherKey="CategoriaID")]
		public EntitySet<Libros> Libros
		{
			get
			{
				return this._Libros;
			}
			set
			{
				this._Libros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Libros(Libros entity)
		{
			this.SendPropertyChanging();
			entity.Categorias = this;
		}
		
		private void detach_Libros(Libros entity)
		{
			this.SendPropertyChanging();
			entity.Categorias = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lenguajes")]
	public partial class Lenguajes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LenguajeID;
		
		private string _NombreLenguaje;
		
		private EntitySet<Libros> _Libros;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLenguajeIDChanging(int value);
    partial void OnLenguajeIDChanged();
    partial void OnNombreLenguajeChanging(string value);
    partial void OnNombreLenguajeChanged();
    #endregion
		
		public Lenguajes()
		{
			this._Libros = new EntitySet<Libros>(new Action<Libros>(this.attach_Libros), new Action<Libros>(this.detach_Libros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LenguajeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LenguajeID
		{
			get
			{
				return this._LenguajeID;
			}
			set
			{
				if ((this._LenguajeID != value))
				{
					this.OnLenguajeIDChanging(value);
					this.SendPropertyChanging();
					this._LenguajeID = value;
					this.SendPropertyChanged("LenguajeID");
					this.OnLenguajeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreLenguaje", DbType="NVarChar(50)")]
		public string NombreLenguaje
		{
			get
			{
				return this._NombreLenguaje;
			}
			set
			{
				if ((this._NombreLenguaje != value))
				{
					this.OnNombreLenguajeChanging(value);
					this.SendPropertyChanging();
					this._NombreLenguaje = value;
					this.SendPropertyChanged("NombreLenguaje");
					this.OnNombreLenguajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lenguajes_Libros", Storage="_Libros", ThisKey="LenguajeID", OtherKey="LenguajeID")]
		public EntitySet<Libros> Libros
		{
			get
			{
				return this._Libros;
			}
			set
			{
				this._Libros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Libros(Libros entity)
		{
			this.SendPropertyChanging();
			entity.Lenguajes = this;
		}
		
		private void detach_Libros(Libros entity)
		{
			this.SendPropertyChanging();
			entity.Lenguajes = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Venta_Detalle")]
	public partial class Venta_Detalle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VentaDetalleID;
		
		private System.Nullable<int> _VentaID;
		
		private System.Nullable<int> _LibroID;
		
		private System.Nullable<int> _Cantidad;
		
		private System.Nullable<decimal> _Precio;
		
		private EntityRef<Ventas> _Ventas;
		
		private EntityRef<Libros> _Libros;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVentaDetalleIDChanging(int value);
    partial void OnVentaDetalleIDChanged();
    partial void OnVentaIDChanging(System.Nullable<int> value);
    partial void OnVentaIDChanged();
    partial void OnLibroIDChanging(System.Nullable<int> value);
    partial void OnLibroIDChanged();
    partial void OnCantidadChanging(System.Nullable<int> value);
    partial void OnCantidadChanged();
    partial void OnPrecioChanging(System.Nullable<decimal> value);
    partial void OnPrecioChanged();
    #endregion
		
		public Venta_Detalle()
		{
			this._Ventas = default(EntityRef<Ventas>);
			this._Libros = default(EntityRef<Libros>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VentaDetalleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int VentaDetalleID
		{
			get
			{
				return this._VentaDetalleID;
			}
			set
			{
				if ((this._VentaDetalleID != value))
				{
					this.OnVentaDetalleIDChanging(value);
					this.SendPropertyChanging();
					this._VentaDetalleID = value;
					this.SendPropertyChanged("VentaDetalleID");
					this.OnVentaDetalleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VentaID", DbType="Int")]
		public System.Nullable<int> VentaID
		{
			get
			{
				return this._VentaID;
			}
			set
			{
				if ((this._VentaID != value))
				{
					if (this._Ventas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVentaIDChanging(value);
					this.SendPropertyChanging();
					this._VentaID = value;
					this.SendPropertyChanged("VentaID");
					this.OnVentaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LibroID", DbType="Int")]
		public System.Nullable<int> LibroID
		{
			get
			{
				return this._LibroID;
			}
			set
			{
				if ((this._LibroID != value))
				{
					if (this._Libros.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLibroIDChanging(value);
					this.SendPropertyChanging();
					this._LibroID = value;
					this.SendPropertyChanged("LibroID");
					this.OnLibroIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Money")]
		public System.Nullable<decimal> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ventas_Venta_Detalle", Storage="_Ventas", ThisKey="VentaID", OtherKey="VentaID", IsForeignKey=true)]
		public Ventas Ventas
		{
			get
			{
				return this._Ventas.Entity;
			}
			set
			{
				Ventas previousValue = this._Ventas.Entity;
				if (((previousValue != value) 
							|| (this._Ventas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ventas.Entity = null;
						previousValue.Venta_Detalle.Remove(this);
					}
					this._Ventas.Entity = value;
					if ((value != null))
					{
						value.Venta_Detalle.Add(this);
						this._VentaID = value.VentaID;
					}
					else
					{
						this._VentaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Ventas");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Libros_Venta_Detalle", Storage="_Libros", ThisKey="LibroID", OtherKey="LibroID", IsForeignKey=true)]
		public Libros Libros
		{
			get
			{
				return this._Libros.Entity;
			}
			set
			{
				Libros previousValue = this._Libros.Entity;
				if (((previousValue != value) 
							|| (this._Libros.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Libros.Entity = null;
						previousValue.Venta_Detalle.Remove(this);
					}
					this._Libros.Entity = value;
					if ((value != null))
					{
						value.Venta_Detalle.Add(this);
						this._LibroID = value.LibroID;
					}
					else
					{
						this._LibroID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Libros");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ventas")]
	public partial class Ventas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VentaID;
		
		private System.Nullable<int> _ClienteID;
		
		private System.Nullable<int> _UsuarioID;
		
		private System.Nullable<System.DateTime> _FechaRenta;
		
		private System.Nullable<System.DateTime> _FechaDevolucion;
		
		private System.Nullable<decimal> _Total;
		
		private System.Nullable<System.DateTime> _FechaRealDevolucion;
		
		private System.Nullable<decimal> _Multa;
		
		private EntitySet<Venta_Detalle> _Venta_Detalle;
		
		private EntityRef<Clientes> _Clientes;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVentaIDChanging(int value);
    partial void OnVentaIDChanged();
    partial void OnClienteIDChanging(System.Nullable<int> value);
    partial void OnClienteIDChanged();
    partial void OnUsuarioIDChanging(System.Nullable<int> value);
    partial void OnUsuarioIDChanged();
    partial void OnFechaRentaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaRentaChanged();
    partial void OnFechaDevolucionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaDevolucionChanged();
    partial void OnTotalChanging(System.Nullable<decimal> value);
    partial void OnTotalChanged();
    partial void OnFechaRealDevolucionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaRealDevolucionChanged();
    partial void OnMultaChanging(System.Nullable<decimal> value);
    partial void OnMultaChanged();
    #endregion
		
		public Ventas()
		{
			this._Venta_Detalle = new EntitySet<Venta_Detalle>(new Action<Venta_Detalle>(this.attach_Venta_Detalle), new Action<Venta_Detalle>(this.detach_Venta_Detalle));
			this._Clientes = default(EntityRef<Clientes>);
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VentaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int VentaID
		{
			get
			{
				return this._VentaID;
			}
			set
			{
				if ((this._VentaID != value))
				{
					this.OnVentaIDChanging(value);
					this.SendPropertyChanging();
					this._VentaID = value;
					this.SendPropertyChanged("VentaID");
					this.OnVentaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClienteID", DbType="Int")]
		public System.Nullable<int> ClienteID
		{
			get
			{
				return this._ClienteID;
			}
			set
			{
				if ((this._ClienteID != value))
				{
					if (this._Clientes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClienteIDChanging(value);
					this.SendPropertyChanging();
					this._ClienteID = value;
					this.SendPropertyChanged("ClienteID");
					this.OnClienteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", DbType="Int")]
		public System.Nullable<int> UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuarioIDChanging(value);
					this.SendPropertyChanging();
					this._UsuarioID = value;
					this.SendPropertyChanged("UsuarioID");
					this.OnUsuarioIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRenta", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaRenta
		{
			get
			{
				return this._FechaRenta;
			}
			set
			{
				if ((this._FechaRenta != value))
				{
					this.OnFechaRentaChanging(value);
					this.SendPropertyChanging();
					this._FechaRenta = value;
					this.SendPropertyChanged("FechaRenta");
					this.OnFechaRentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDevolucion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaDevolucion
		{
			get
			{
				return this._FechaDevolucion;
			}
			set
			{
				if ((this._FechaDevolucion != value))
				{
					this.OnFechaDevolucionChanging(value);
					this.SendPropertyChanging();
					this._FechaDevolucion = value;
					this.SendPropertyChanged("FechaDevolucion");
					this.OnFechaDevolucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Money")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRealDevolucion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaRealDevolucion
		{
			get
			{
				return this._FechaRealDevolucion;
			}
			set
			{
				if ((this._FechaRealDevolucion != value))
				{
					this.OnFechaRealDevolucionChanging(value);
					this.SendPropertyChanging();
					this._FechaRealDevolucion = value;
					this.SendPropertyChanged("FechaRealDevolucion");
					this.OnFechaRealDevolucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Multa", DbType="Money")]
		public System.Nullable<decimal> Multa
		{
			get
			{
				return this._Multa;
			}
			set
			{
				if ((this._Multa != value))
				{
					this.OnMultaChanging(value);
					this.SendPropertyChanging();
					this._Multa = value;
					this.SendPropertyChanged("Multa");
					this.OnMultaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ventas_Venta_Detalle", Storage="_Venta_Detalle", ThisKey="VentaID", OtherKey="VentaID")]
		public EntitySet<Venta_Detalle> Venta_Detalle
		{
			get
			{
				return this._Venta_Detalle;
			}
			set
			{
				this._Venta_Detalle.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Clientes_Ventas", Storage="_Clientes", ThisKey="ClienteID", OtherKey="ClienteID", IsForeignKey=true)]
		public Clientes Clientes
		{
			get
			{
				return this._Clientes.Entity;
			}
			set
			{
				Clientes previousValue = this._Clientes.Entity;
				if (((previousValue != value) 
							|| (this._Clientes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Clientes.Entity = null;
						previousValue.Ventas.Remove(this);
					}
					this._Clientes.Entity = value;
					if ((value != null))
					{
						value.Ventas.Add(this);
						this._ClienteID = value.ClienteID;
					}
					else
					{
						this._ClienteID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Clientes");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Ventas", Storage="_Usuarios", ThisKey="UsuarioID", OtherKey="UsuarioID", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.Ventas.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.Ventas.Add(this);
						this._UsuarioID = value.UsuarioID;
					}
					else
					{
						this._UsuarioID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Venta_Detalle(Venta_Detalle entity)
		{
			this.SendPropertyChanging();
			entity.Ventas = this;
		}
		
		private void detach_Venta_Detalle(Venta_Detalle entity)
		{
			this.SendPropertyChanging();
			entity.Ventas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Libros")]
	public partial class Libros : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LibroID;
		
		private string _Titulo;
		
		private string _ISBN;
		
		private System.Nullable<int> _CategoriaID;
		
		private System.Nullable<int> _AutorID;
		
		private System.Nullable<int> _EditorialID;
		
		private System.Nullable<int> _LenguajeID;
		
		private System.Nullable<int> _Stock;
		
		private string _Tipo;
		
		private System.Nullable<decimal> _Precio;
		
		private EntitySet<Venta_Detalle> _Venta_Detalle;
		
		private EntityRef<Autores> _Autores;
		
		private EntityRef<Categorias> _Categorias;
		
		private EntityRef<Editoriales> _Editoriales;
		
		private EntityRef<Lenguajes> _Lenguajes;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLibroIDChanging(int value);
    partial void OnLibroIDChanged();
    partial void OnTituloChanging(string value);
    partial void OnTituloChanged();
    partial void OnISBNChanging(string value);
    partial void OnISBNChanged();
    partial void OnCategoriaIDChanging(System.Nullable<int> value);
    partial void OnCategoriaIDChanged();
    partial void OnAutorIDChanging(System.Nullable<int> value);
    partial void OnAutorIDChanged();
    partial void OnEditorialIDChanging(System.Nullable<int> value);
    partial void OnEditorialIDChanged();
    partial void OnLenguajeIDChanging(System.Nullable<int> value);
    partial void OnLenguajeIDChanged();
    partial void OnStockChanging(System.Nullable<int> value);
    partial void OnStockChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnPrecioChanging(System.Nullable<decimal> value);
    partial void OnPrecioChanged();
    #endregion
		
		public Libros()
		{
			this._Venta_Detalle = new EntitySet<Venta_Detalle>(new Action<Venta_Detalle>(this.attach_Venta_Detalle), new Action<Venta_Detalle>(this.detach_Venta_Detalle));
			this._Autores = default(EntityRef<Autores>);
			this._Categorias = default(EntityRef<Categorias>);
			this._Editoriales = default(EntityRef<Editoriales>);
			this._Lenguajes = default(EntityRef<Lenguajes>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LibroID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LibroID
		{
			get
			{
				return this._LibroID;
			}
			set
			{
				if ((this._LibroID != value))
				{
					this.OnLibroIDChanging(value);
					this.SendPropertyChanging();
					this._LibroID = value;
					this.SendPropertyChanged("LibroID");
					this.OnLibroIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="NVarChar(100)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this.OnTituloChanging(value);
					this.SendPropertyChanging();
					this._Titulo = value;
					this.SendPropertyChanged("Titulo");
					this.OnTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBN", DbType="NVarChar(20)")]
		public string ISBN
		{
			get
			{
				return this._ISBN;
			}
			set
			{
				if ((this._ISBN != value))
				{
					this.OnISBNChanging(value);
					this.SendPropertyChanging();
					this._ISBN = value;
					this.SendPropertyChanged("ISBN");
					this.OnISBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaID", DbType="Int")]
		public System.Nullable<int> CategoriaID
		{
			get
			{
				return this._CategoriaID;
			}
			set
			{
				if ((this._CategoriaID != value))
				{
					if (this._Categorias.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCategoriaIDChanging(value);
					this.SendPropertyChanging();
					this._CategoriaID = value;
					this.SendPropertyChanged("CategoriaID");
					this.OnCategoriaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutorID", DbType="Int")]
		public System.Nullable<int> AutorID
		{
			get
			{
				return this._AutorID;
			}
			set
			{
				if ((this._AutorID != value))
				{
					if (this._Autores.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAutorIDChanging(value);
					this.SendPropertyChanging();
					this._AutorID = value;
					this.SendPropertyChanged("AutorID");
					this.OnAutorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditorialID", DbType="Int")]
		public System.Nullable<int> EditorialID
		{
			get
			{
				return this._EditorialID;
			}
			set
			{
				if ((this._EditorialID != value))
				{
					if (this._Editoriales.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEditorialIDChanging(value);
					this.SendPropertyChanging();
					this._EditorialID = value;
					this.SendPropertyChanged("EditorialID");
					this.OnEditorialIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LenguajeID", DbType="Int")]
		public System.Nullable<int> LenguajeID
		{
			get
			{
				return this._LenguajeID;
			}
			set
			{
				if ((this._LenguajeID != value))
				{
					if (this._Lenguajes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLenguajeIDChanging(value);
					this.SendPropertyChanging();
					this._LenguajeID = value;
					this.SendPropertyChanged("LenguajeID");
					this.OnLenguajeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stock", DbType="Int")]
		public System.Nullable<int> Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				if ((this._Stock != value))
				{
					this.OnStockChanging(value);
					this.SendPropertyChanging();
					this._Stock = value;
					this.SendPropertyChanged("Stock");
					this.OnStockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="NVarChar(50)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Money")]
		public System.Nullable<decimal> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Libros_Venta_Detalle", Storage="_Venta_Detalle", ThisKey="LibroID", OtherKey="LibroID")]
		public EntitySet<Venta_Detalle> Venta_Detalle
		{
			get
			{
				return this._Venta_Detalle;
			}
			set
			{
				this._Venta_Detalle.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Autores_Libros", Storage="_Autores", ThisKey="AutorID", OtherKey="AutorID", IsForeignKey=true)]
		public Autores Autores
		{
			get
			{
				return this._Autores.Entity;
			}
			set
			{
				Autores previousValue = this._Autores.Entity;
				if (((previousValue != value) 
							|| (this._Autores.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Autores.Entity = null;
						previousValue.Libros.Remove(this);
					}
					this._Autores.Entity = value;
					if ((value != null))
					{
						value.Libros.Add(this);
						this._AutorID = value.AutorID;
					}
					else
					{
						this._AutorID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Autores");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorias_Libros", Storage="_Categorias", ThisKey="CategoriaID", OtherKey="CategoriaID", IsForeignKey=true)]
		public Categorias Categorias
		{
			get
			{
				return this._Categorias.Entity;
			}
			set
			{
				Categorias previousValue = this._Categorias.Entity;
				if (((previousValue != value) 
							|| (this._Categorias.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categorias.Entity = null;
						previousValue.Libros.Remove(this);
					}
					this._Categorias.Entity = value;
					if ((value != null))
					{
						value.Libros.Add(this);
						this._CategoriaID = value.CategoriaID;
					}
					else
					{
						this._CategoriaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Categorias");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Editoriales_Libros", Storage="_Editoriales", ThisKey="EditorialID", OtherKey="EditorialID", IsForeignKey=true)]
		public Editoriales Editoriales
		{
			get
			{
				return this._Editoriales.Entity;
			}
			set
			{
				Editoriales previousValue = this._Editoriales.Entity;
				if (((previousValue != value) 
							|| (this._Editoriales.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Editoriales.Entity = null;
						previousValue.Libros.Remove(this);
					}
					this._Editoriales.Entity = value;
					if ((value != null))
					{
						value.Libros.Add(this);
						this._EditorialID = value.EditorialID;
					}
					else
					{
						this._EditorialID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Editoriales");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lenguajes_Libros", Storage="_Lenguajes", ThisKey="LenguajeID", OtherKey="LenguajeID", IsForeignKey=true)]
		public Lenguajes Lenguajes
		{
			get
			{
				return this._Lenguajes.Entity;
			}
			set
			{
				Lenguajes previousValue = this._Lenguajes.Entity;
				if (((previousValue != value) 
							|| (this._Lenguajes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Lenguajes.Entity = null;
						previousValue.Libros.Remove(this);
					}
					this._Lenguajes.Entity = value;
					if ((value != null))
					{
						value.Libros.Add(this);
						this._LenguajeID = value.LenguajeID;
					}
					else
					{
						this._LenguajeID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Lenguajes");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Venta_Detalle(Venta_Detalle entity)
		{
			this.SendPropertyChanging();
			entity.Libros = this;
		}
		
		private void detach_Venta_Detalle(Venta_Detalle entity)
		{
			this.SendPropertyChanging();
			entity.Libros = null;
		}
	}
	
	public partial class sp_LeerClienteResult
	{
		
		private int _ClienteID;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Email;
		
		public sp_LeerClienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClienteID", DbType="Int NOT NULL")]
		public int ClienteID
		{
			get
			{
				return this._ClienteID;
			}
			set
			{
				if ((this._ClienteID != value))
				{
					this._ClienteID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(100)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
	}
	
	public partial class sp_ListarClientesResult
	{
		
		private int _ClienteID;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Email;
		
		public sp_ListarClientesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClienteID", DbType="Int NOT NULL")]
		public int ClienteID
		{
			get
			{
				return this._ClienteID;
			}
			set
			{
				if ((this._ClienteID != value))
				{
					this._ClienteID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(100)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
	}
	
	public partial class sp_LeerUsuarioResult
	{
		
		private int _UsuarioID;
		
		private string _NombreUsuario;
		
		private string _Correo;
		
		private string _Contraseña;
		
		private string _Rol;
		
		private System.Nullable<System.DateTime> _FechaCreacion;
		
		public sp_LeerUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", DbType="Int NOT NULL")]
		public int UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					this._UsuarioID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="NVarChar(50)")]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this._NombreUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="NVarChar(50)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="NVarChar(50)")]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this._Contraseña = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="NVarChar(20)")]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this._Rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this._FechaCreacion = value;
				}
			}
		}
	}
	
	public partial class sp_ListarUsuariosResult
	{
		
		private int _UsuarioID;
		
		private string _NombreUsuario;
		
		private string _Correo;
		
		private string _Contraseña;
		
		private string _Rol;
		
		private System.Nullable<System.DateTime> _FechaCreacion;
		
		public sp_ListarUsuariosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", DbType="Int NOT NULL")]
		public int UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					this._UsuarioID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="NVarChar(50)")]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this._NombreUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="NVarChar(50)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="NVarChar(50)")]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this._Contraseña = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="NVarChar(20)")]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this._Rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this._FechaCreacion = value;
				}
			}
		}
	}
	
	public partial class sp_ListarAutoresResult
	{
		
		private int _AutorID;
		
		private string _Nombre;
		
		private string _Apellido;
		
		public sp_ListarAutoresResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutorID", DbType="Int NOT NULL")]
		public int AutorID
		{
			get
			{
				return this._AutorID;
			}
			set
			{
				if ((this._AutorID != value))
				{
					this._AutorID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
	}
	
	public partial class sp_ListarEditorialesResult
	{
		
		private int _EditorialID;
		
		private string _NombreEditorial;
		
		public sp_ListarEditorialesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditorialID", DbType="Int NOT NULL")]
		public int EditorialID
		{
			get
			{
				return this._EditorialID;
			}
			set
			{
				if ((this._EditorialID != value))
				{
					this._EditorialID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEditorial", DbType="NVarChar(50)")]
		public string NombreEditorial
		{
			get
			{
				return this._NombreEditorial;
			}
			set
			{
				if ((this._NombreEditorial != value))
				{
					this._NombreEditorial = value;
				}
			}
		}
	}
	
	public partial class sp_ListarCategoriasResult
	{
		
		private int _CategoriaID;
		
		private string _NombreCategoria;
		
		public sp_ListarCategoriasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaID", DbType="Int NOT NULL")]
		public int CategoriaID
		{
			get
			{
				return this._CategoriaID;
			}
			set
			{
				if ((this._CategoriaID != value))
				{
					this._CategoriaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCategoria", DbType="NVarChar(50)")]
		public string NombreCategoria
		{
			get
			{
				return this._NombreCategoria;
			}
			set
			{
				if ((this._NombreCategoria != value))
				{
					this._NombreCategoria = value;
				}
			}
		}
	}
	
	public partial class sp_ListarLenguajesResult
	{
		
		private int _LenguajeID;
		
		private string _NombreLenguaje;
		
		public sp_ListarLenguajesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LenguajeID", DbType="Int NOT NULL")]
		public int LenguajeID
		{
			get
			{
				return this._LenguajeID;
			}
			set
			{
				if ((this._LenguajeID != value))
				{
					this._LenguajeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreLenguaje", DbType="NVarChar(50)")]
		public string NombreLenguaje
		{
			get
			{
				return this._NombreLenguaje;
			}
			set
			{
				if ((this._NombreLenguaje != value))
				{
					this._NombreLenguaje = value;
				}
			}
		}
	}
	
	public partial class sp_ListarVentasResult
	{
		
		private int _VentaID;
		
		private System.Nullable<int> _ClienteID;
		
		private System.Nullable<int> _UsuarioID;
		
		private System.Nullable<System.DateTime> _FechaRenta;
		
		private System.Nullable<System.DateTime> _FechaDevolucion;
		
		private System.Nullable<decimal> _Total;
		
		private System.Nullable<System.DateTime> _FechaRealDevolucion;
		
		private System.Nullable<decimal> _Multa;
		
		public sp_ListarVentasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VentaID", DbType="Int NOT NULL")]
		public int VentaID
		{
			get
			{
				return this._VentaID;
			}
			set
			{
				if ((this._VentaID != value))
				{
					this._VentaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClienteID", DbType="Int")]
		public System.Nullable<int> ClienteID
		{
			get
			{
				return this._ClienteID;
			}
			set
			{
				if ((this._ClienteID != value))
				{
					this._ClienteID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", DbType="Int")]
		public System.Nullable<int> UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					this._UsuarioID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRenta", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaRenta
		{
			get
			{
				return this._FechaRenta;
			}
			set
			{
				if ((this._FechaRenta != value))
				{
					this._FechaRenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDevolucion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaDevolucion
		{
			get
			{
				return this._FechaDevolucion;
			}
			set
			{
				if ((this._FechaDevolucion != value))
				{
					this._FechaDevolucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Money")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRealDevolucion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaRealDevolucion
		{
			get
			{
				return this._FechaRealDevolucion;
			}
			set
			{
				if ((this._FechaRealDevolucion != value))
				{
					this._FechaRealDevolucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Multa", DbType="Money")]
		public System.Nullable<decimal> Multa
		{
			get
			{
				return this._Multa;
			}
			set
			{
				if ((this._Multa != value))
				{
					this._Multa = value;
				}
			}
		}
	}
	
	public partial class sp_ListarVentaDetalleResult
	{
		
		private int _VentaDetalleID;
		
		private System.Nullable<int> _VentaID;
		
		private System.Nullable<int> _LibroID;
		
		private System.Nullable<int> _Cantidad;
		
		private System.Nullable<decimal> _Precio;
		
		public sp_ListarVentaDetalleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VentaDetalleID", DbType="Int NOT NULL")]
		public int VentaDetalleID
		{
			get
			{
				return this._VentaDetalleID;
			}
			set
			{
				if ((this._VentaDetalleID != value))
				{
					this._VentaDetalleID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VentaID", DbType="Int")]
		public System.Nullable<int> VentaID
		{
			get
			{
				return this._VentaID;
			}
			set
			{
				if ((this._VentaID != value))
				{
					this._VentaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LibroID", DbType="Int")]
		public System.Nullable<int> LibroID
		{
			get
			{
				return this._LibroID;
			}
			set
			{
				if ((this._LibroID != value))
				{
					this._LibroID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Money")]
		public System.Nullable<decimal> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this._Precio = value;
				}
			}
		}
	}
	
	public partial class sp_ListarLibrosResult
	{
		
		private int _LibroID;
		
		private string _Titulo;
		
		private string _ISBN;
		
		private System.Nullable<int> _CategoriaID;
		
		private System.Nullable<int> _AutorID;
		
		private System.Nullable<int> _EditorialID;
		
		private System.Nullable<int> _LenguajeID;
		
		private System.Nullable<int> _Stock;
		
		private string _Tipo;
		
		private System.Nullable<decimal> _Precio;
		
		public sp_ListarLibrosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LibroID", DbType="Int NOT NULL")]
		public int LibroID
		{
			get
			{
				return this._LibroID;
			}
			set
			{
				if ((this._LibroID != value))
				{
					this._LibroID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="NVarChar(100)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this._Titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBN", DbType="NVarChar(20)")]
		public string ISBN
		{
			get
			{
				return this._ISBN;
			}
			set
			{
				if ((this._ISBN != value))
				{
					this._ISBN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaID", DbType="Int")]
		public System.Nullable<int> CategoriaID
		{
			get
			{
				return this._CategoriaID;
			}
			set
			{
				if ((this._CategoriaID != value))
				{
					this._CategoriaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutorID", DbType="Int")]
		public System.Nullable<int> AutorID
		{
			get
			{
				return this._AutorID;
			}
			set
			{
				if ((this._AutorID != value))
				{
					this._AutorID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditorialID", DbType="Int")]
		public System.Nullable<int> EditorialID
		{
			get
			{
				return this._EditorialID;
			}
			set
			{
				if ((this._EditorialID != value))
				{
					this._EditorialID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LenguajeID", DbType="Int")]
		public System.Nullable<int> LenguajeID
		{
			get
			{
				return this._LenguajeID;
			}
			set
			{
				if ((this._LenguajeID != value))
				{
					this._LenguajeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stock", DbType="Int")]
		public System.Nullable<int> Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				if ((this._Stock != value))
				{
					this._Stock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="NVarChar(50)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Money")]
		public System.Nullable<decimal> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this._Precio = value;
				}
			}
		}
	}
	
	public partial class sp_VistaVentasResult
	{
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<System.DateTime> _FechaRenta;
		
		private System.Nullable<System.DateTime> _FechaDevolucion;
		
		private System.Nullable<decimal> _Total;
		
		private System.Nullable<System.DateTime> _FechaRealDevolucion;
		
		private System.Nullable<decimal> _Multa;
		
		public sp_VistaVentasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRenta", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaRenta
		{
			get
			{
				return this._FechaRenta;
			}
			set
			{
				if ((this._FechaRenta != value))
				{
					this._FechaRenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDevolucion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaDevolucion
		{
			get
			{
				return this._FechaDevolucion;
			}
			set
			{
				if ((this._FechaDevolucion != value))
				{
					this._FechaDevolucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Money")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRealDevolucion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaRealDevolucion
		{
			get
			{
				return this._FechaRealDevolucion;
			}
			set
			{
				if ((this._FechaRealDevolucion != value))
				{
					this._FechaRealDevolucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Multa", DbType="Money")]
		public System.Nullable<decimal> Multa
		{
			get
			{
				return this._Multa;
			}
			set
			{
				if ((this._Multa != value))
				{
					this._Multa = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
